server.port: 8080
micro.svc.one.uri : http://micro_svc_one:8080/micro_one/api
micro.svc.two.uri : http://micro_svc_two:8080/micro_two/api
spring.datasource.username : primary_user
spring.datasource.password : primary_password
spring.datasource.hibernate.default_schema : public
spring.datasource.driver-class-name:  org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://primary_svc-db:5432/primary_svc
#spring.datasource.url: jdbc:postgresql://localhost:8432/primary_svc
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
