server.port: 8080
micro.svc.one.uri : http://micro_svc_one:8080/api/micro_one
micro.svc.two.uri : http://micro_svc_two:8080/api/micro_two
spring.datasource.username : primary_user
spring.datasource.password : primary_password
spring.datasource.hibernate.default_schema : public
spring.datasource.driver-class-name:  org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://primary_svc-db:5432/primary_svc
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging.file : log/application.log
logging.pattern.level : "%X{mdcData}%5p"
