es:
  image: elasticsearch:latest
  volumes:
    - ${PWD}/es-data:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 1g
  cap_add:
    - IPC_LOCK

kibana:
  image: kibana
  ports:
    - 5601:5601
  environment:
    - elasticsearch.password=password
  links:
    - es:elasticsearch

fluentd:
  build: fluent-es/
  ports:
    - 24224:24224
  volumes:
    - ${PWD}/log:/fluent/log
  links:
    - es:elasticsearch
